export const SESSION_STARTED = 'XMPP/SESSION_STARTED';

export const MUC_JOIN_START = 'XMPP/MUC_JOIN_START';
export const MUC_JOIN_SUCCESS = 'XMPP/MUC_JOIN_SUCCESS';
export const MUC_JOIN_ERROR = 'XMPP/MUC_JOIN_ERROR';
export const MUC_RECEIVE_GROUPCHAT = 'XMPP/MUC_RECEIVE_GROUPCHAT';
